### ISSUE TITLE
Error getting access token: AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/msgraph-training-dotnet-core#2] opened 2019-10-04 16:47 UTC
Maybe a change in MSAL as this tutorial was working correctly.

The code has this:
```
        public DeviceCodeAuthProvider(string appId, string[] scopes)

        {

            _scopes = scopes;

 

            _msalClient = PublicClientApplicationBuilder

                .Create(appId)

                // Set the tenant ID to "organizations" to disable personal accounts

                // Azure OAuth does not support device code flow for personal accounts

                // See https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-device-code

                .WithTenantId("organizations")

                .Build();

        }
```
Following the documentation for WithTenantId (https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractapplicationbuilder-1.withtenantid?view=azure-dotnet) , you see this

`public T WithTenantId (string tenantId);`

tenant ID of the Azure AD tenant or a domain associated with this Azure AD tenant, in order to sign-in a user of a specific organization only

**Problem**

The demo seems to suggest something different from what the API/SDK does. Once I replaced “organizations” with MSFT actual tenant ID, things worked.

**Comment by jthake-msft** [comment] 2019-10-04 17:48
I actually got this working with my developer tenant fine. So it may be an issue just with our microsoft.com tenant. When I tried it I actually couldn't get past the , requires admin consent using my corp account.

**Comment by jasonjoh** [comment] 2019-10-07 13:23
I don't reproduce this. Let's compare setups.

- I have an app registered in a demo tenant as a multi-tenant app (basically following the instructions in the tutorial)
- I log in to the app "as-is" with my microsoft.com account, and I get the message that the app needs access to resources that an admin has to approve (expected due to how our org is configured).
- I remove Calendars.Read from the requested scope, leaving User.Read and re-run it, it works. I get back an access token and parsing it in jwt.ms shows it has all the expected claims.

It's possible that Azure changed something between Friday and today, maybe retry your repro?

**Comment by jasonjoh** [comment] 2019-10-07 13:38
I also want to point out that it does not "suggest something different from what the API/SDK does." The very first paragraph of the linked doc states:

> Sets the Tenant Id of the organization from which the application will let users sign-in. This is classically a GUID or a domain name. See https://aka.ms/msal-net-application-configuration. Although it is also possible to set tenantId to common, organizations, and consumers, it's recommended to use one of the overrides of WithAuthority(AzureCloudInstance, AadAuthorityAudience, Boolean).

`organizations` is absolutely a valid value here.

**Comment by jasonjoh** [comment] 2020-01-09 13:16
Closing this issue as the code now uses `.WithAuthority(AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount, true)` instead of `WithTenantid`.

**Closed by jasonjoh** 2020-01-09 13:16 UTC
